# Generated by Django 4.2.3 on 2023-07-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
    ]
