# Generated by Django 4.2.3 on 2023-07-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacao", "0002_cargos"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="cargo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="autenticacao.cargos",
            ),
            preserve_default=False,
        ),
    ]
