# Generated by Django 4.2.3 on 2023-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacao", "0003_pessoa_cargo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pessoa",
            name="cargo",
        ),
        migrations.AddField(
            model_name="pessoa",
            name="cargo",
            field=models.ManyToManyField(to="autenticacao.cargos"),
        ),
    ]
